version: "2"

services:
  registry:
    image: registry:2
    restart: always
    volumes:
        - /data/dev/docker-registry:/var/lib/registry
    environment:
        - REGISTRY_HTTP_ADDR=0.0.0.0:5000

  nginx:
    image: nginx:1.13
    restart: always
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./docker-registry.pvt.crt:/root/docker-registry.pvt.crt
        - ./docker-registry.pvt.key:/root/docker-registry.pvt.key
        - ../logs:/var/log/nginx
    ports: 
        - "443:443"
        - "80:80"

