version: "3"

volumes:
  nvidia_driver_375.66:
    external: true

services:
  jupyter:
    image: akharlamov/jupyter:latest
    build: ./jupyter
    ports:
      - 8888:8888
    volumes:
      - /data:/data
      - /data/dev/notebooks:/notebooks
      - nvidia_driver_375.66:/usr/local/nvidia:ro
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm

  keras-mon:
    image: akharlamov/keras-mon:latest
    build: ./keras-mon
    ports:
      - 9000:9000

  lib-tools:
    image: akharlamov/lib-tools:latest
    build: ./lib-tools


